atent/urls.py
from django.urls import path
from . import views

app_name= 'atent'

urlpatterns = [
    path("register/" , views.register , name = 'register'),
    path("login/" , views.login_view , name = 'login'),
    path("logout/" , views.logout_view , name = 'logout'),
    path("forgot-password/", views.forgot_password , name = 'forgot_password'),
    path("reset-password/<str:token>/", views.reset_password , name = 'reset_password')
]

dev/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('auth/' , include('atent.urls')),
    path('' , include('form.urls')),
)

form/urls.py
from django.urls import path
from . import views

app_name = 'form'

urlpatterns = [
    path("" , views.main_dashbord , name = 'index'),
    path("/myform/" , views.my_form , name = 'myform'),
    path("create-form/", views.create_form , name = 'create-form'),
    path("delete-form/<str:form>/" , views.delete_form , name = 'delete-form'),
    path("<str:form>/" , views.form_details , name = 'form_details'),
    
    path("view-form/<uuid:form>/", views.view_form , name = 'view-form'),
    path("submit-form'/<str:form>/", views.submit_form , name = 'submit-form'),
    path("<str:form>/<str:submission>/submissions/", views.view_all_submission , name='all_submission'),
]

form/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


class Form(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Questions(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    label = models.CharField(max_length=100)
    form = models.ForeignKey(Form, on_delete=models.CASCADE)

class Response(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, null=True)

class ResponseQuestion(models.Model):
    question_id = models.UUIDField()
    response = models.CharField(max_length=255)
    response_id = models.UUIDField()

form/views.py
from django.shortcuts import redirect, render
from .models import Form, Questions, Response, ResponseQuestion
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages


def main_dashbord(request):
    return render(request , 'form/index.html')


############ show forms created by user, to see or delete them #################
@login_required(login_url='/auth/login/')
def my_form(request):
    try:
        forms = Form.objects.filter(user__id = request.user.id)[::-1]
    except:
        forms= None
    return render(request , 'form/my_form.html' , {'forms': forms})


#################################### creating form and questions ###################################
@login_required(login_url='/auth/login/')
def create_form(request):
    if request.method == "POST":
        Form(name=request.POST["form-name"] , user_id= request.user.id).save()
        f = Form.objects.filter(name=request.POST["form-name"])[::-1][0]

        for i in range(int(request.POST["questionCount"])):
            try:
                Questions(label=request.POST[str(i)], form=f).save()
            except:
                pass
        return HttpResponseRedirect(reverse('form:myform'))
    return render(request, "form/create.html")


############################### delete form and its Q&A ##########################################
def delete_form(request, form):
    Form.objects.filter(id=form).delete()
    return redirect(reverse('form:myform'))


######### placing questions in form and make form ready to share with participants ##########
def view_form(request, form):
    try:
        f = Form.objects.get(id=form)
    except:
        return HttpResponse("404 Not Found")
    frm = Form.objects.filter(id = form)
    questions = Questions.objects.filter(form__id=f.id)
    formname = frm[0].name
    return render(request, "form/view-form.html", {
        "form": form,
        "questions": questions,
        "name":formname
    })


########## receiving participants answer and create submission ##############################
def submit_form(request, form):
    ############## creating response form ###########
    questions = Questions.objects.filter(form__id = form)
    response = Response(question= questions[0])
    response.save()
    ############## preparing response form ##########
    resp = Response.objects.filter(question= questions[0])[::-1][0]

    ######## connecting questions and answers, and put them in response form #######
    for i in request.POST:
        if i == "csrfmiddlewaretoken":
            continue
        ResponseQuestion(question_id=i, response=request.POST[i], response_id=resp.id).save()

    messages.success(request, "Your answers has been submited:)")
    return redirect(reverse("form:index"))
#    return HttpResponseRedirect(f"/d/{form_id}/{r.id}/")


#############################################################################################


############# user can see form link, questions, and participants answers ################## 
def form_details(request , form):
    frm = Form.objects.get(user_id = request.user.id , id = form)
    question = Questions.objects.filter(form__id = form)[0]
    response = Response.objects.filter(question = question)
    questions = Questions.objects.filter(form__id = form)
    participants = len(question.response_set.all())
    return render(request , "form/form.html" , {'questions': questions,'form': frm ,
     'participants':participants , 'response':response})


################ see participants answers #############################################
def view_all_submission(request, form , submission):
    try:
        form = Form.objects.get(id=form)
        questions = Questions.objects.filter(form__id = form.id)
        ########################################################
        rs = Response.objects.filter(question= questions[0])[::-1]
        rs2 = []
        i = 1
        for r in rs:
            rs2.append([r , i])
            i+=1

        ##############################################################
        rss = ResponseQuestion.objects.filter(response_id = submission)
        data = []
        for r in rss:
            i = Questions.objects.get(id = r.question_id)
            data.append([i.label , r.response])

    except:
        messages.warning(request, "there is no response yet")
        return HttpResponseRedirect(reverse('form:myform'))
    return render(request , 'form/view-response.html' , {'data':data , 'rs':rs2[::-1] , 'form':form})

form/templates/form/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 , shrink-to-fit=no">
    <title>Form maker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>
      $(document).ready(function () {
          $("#close-btn").click(function() {
              $("#div-to-toggle").hide()
          });
      });
  </script>
  </head>
  {% if LANGUAGE_CODE == 'en'%}
    <body class="no-js" lang="en" dir="ltr">
      <div class="navbar">
        <a href="{% url 'form:index' %}" style="color:#31A6A3">home</a>
        <a href="{% url 'form:create-form' %}" style="color:#31A6A3">create form</a>
        <div class="dropdown">
          <button class="dropbtn" style="color:#31A6A3">User
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            {% if user.is_authenticated %}
            <div class="mr-2">
              <div>
                <p style="color:rgb(2, 2, 2); text-align: center; background-color: rgb(247, 247, 247);">{{ user.username }}</p>
              </div>
                  <a href="{% url 'atent:logout'%}" style="color:#31A6A3">Logout</a>
                  <a href="{% url 'atent:forgot_password' %}" style="color:#31A6A3">forget pass</a>
            </div>
            {% else %}
                <a href="{% url 'atent:login'%}" style="color:#31A6A3">Login</a>
                <a href="{% url 'atent:register' %}" style="color:#31A6A3">Register</a>
            {% endif %}
          </div>
        </div>
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
          <select style="background-color:#31A6A3" name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <option style="background-color:#31A6A3" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
              {{ language.name_local }} ({{ language.code }})
            </option>
            {% endfor %}
          </select>
          <input style="background-color:#31A6A3" type="submit" value="{% translate 'Go' %}">
        </form>
        <a href="{% url 'form:myform' %}" style="color:#31A6A3">My form</a>
      </div>


      <div id="content" , name = "content" , class="main">
        <h1 class="mt-2">{% translate 'Form maker' %}</h1>
        <hr class="mt-0 mb-4">
        {% include 'form/includes/messages.html' %}
        {% block content %}
        {% endblock %}
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="
      sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
  {% else %}
    <body class="no-js" lang="en" dir="rtl">
      <div class="navbar">
          <a href="{% url 'form:index' %}" style="color:#31A6A3">خانه</a>
        <a href="{% url 'form:create-form' %}" style="color:#31A6A3">ساخت فرم</a>
        <div class="dropdown">
            <button class="dropbtn" style="color:#31A6A3">کاربر
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content" dir="rtl">
              {% if user.is_authenticated %}
                <div class="mr-2">
                  <div>
                    <p style="color:rgb(2, 2, 2); text-align: center; background-color: rgb(247, 247, 247);">{{ user.username }}</p>
                  </div>
                      <a href="{% url 'atent:logout'%}" style="color:#31A6A3">خروج</a>
                      <a href="{% url 'atent:forgot_password' %}" style="color:#31A6A3">فراموشی رمز</a>
                </div>
              {% else %}
                  <a href="{% url 'atent:login'%}" style="color:#31A6A3">ورود</a>
                  <a href="{% url 'atent:register' %}" style="color:#31A6A3">ثبت نام</a>
              {% endif %}
              </div>
          </div>
          <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
            <select style="background-color:#31A6A3" name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
              <option style="background-color:#31A6A3" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
              </option>
              {% endfor %}
            </select>
            <input style="background-color:#31A6A3" type="submit" value="{% translate 'Go' %}">
          </form>
        <a href="{% url 'form:myform' %}" style="color:#31A6A3">فرم های من</a>
      </div>
    <div id="content" , name = "content" , class="main">
      <h1 class="mt-2">{% translate 'Form maker' %}</h1>
      <hr class="mt-0 mb-4">
      {% include 'form/includes/messages.html' %}
      {% block contant %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="
    sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>

  </html>
{% endif %}

form/templates/form/create.html
{% extends "form/base.html" %}
{% load static %}
{% load i18n %}
{% if LANGUAGE_CODE == 'en'%}
  {% block content %}
    {% if message %}
    <div>
      <h5>{{ message|safe }}</h5>
    </div>
    {% endif %}

    {% block title %}
        <h4>Create new form</h4><br>
    {% endblock %}

    {% block main %}
        <form method="POST" id="form">
            {% csrf_token %}
            <div class="col-sm-10">
                <input type="text" name="form-name" placeholder="Form Name" class="form-control">
                <br>
                <div id="questions">
                </div>
                <br>
                <button type="button" class="btn btn-primary" onclick="createNewQuestion();">Create a new question</button>
                <button id="submit-btn" type="button" class="btn btn-dark" onclick="submitForm();" disabled>Create this form</button>
            </div>
        </form>
        <script>
            var list=[];
            var questionCount = 0;
            function createNewQuestion() {
                var DIV = document.createElement("div");
                var BR = document.createElement("BR");
                DIV.setAttribute('class' , 'round3');
                DIV.setAttribute("id", questionCount);
                DIV.innerHTML = `<input type="text" name="${questionCount}" placeholder='Enter your question prompt here: ''
                class="form-control"><br>
                <button type="button" onclick='deleteQuestion(${questionCount});'
                class='btn btn-danger'>Delete This Question</button>`;
                BR.setAttribute("id", `br-${questionCount}`)
                document.getElementById("questions").appendChild(DIV);
                document.getElementById("questions").appendChild(BR);
                questionCount++;
                list.push(questionCount);
                if (list.length <1 ) {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= true;
                } else {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= false;
                }
            }

            function submitForm() {
                var INPUT = document.createElement("input");
                INPUT.setAttribute("type", "hidden");
                INPUT.setAttribute("name", "questionCount")
                INPUT.setAttribute("value", questionCount)
                document.getElementById("form").appendChild(INPUT);
                document.getElementById("form").submit();
            }

            function deleteQuestion(name) {
                document.getElementById(`br-${name}`).remove()
                document.getElementById(name).remove()
                list.pop();
                if (list.length <1 ) {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= true;
                } else {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= false;
                }
            }
        </script>
    {% endblock %}
  {% endblock %}
{% else %}
  {% block contant %}
    {% if message %}
    <div>
      <h5>{{ message|safe }}</h5>
    </div>
    {% endif %}

    {% block titla %}
        <h4>ساخت فرم جدید</h4><br>
    {% endblock %}

    {% block maain %}
        <form method="POST" id="form">
            {% csrf_token %}
            <div class="col-sm-10">
                <input type="text" name="form-name" placeholder="نام فرم" class="form-control">
                <br>
                <div id="questions">
                </div>
                <br>
                <button type="button" class="btn btn-primary" onclick="createNewQuestion();">افزودن سوال جدید</button>
                <button id="submit-btn" type="button" class="btn btn-dark" onclick="submitForm();" disabled>ساخت فرم</button>
            </div>
        </form>
        <script>
            var list= [];
            var questionCount = 0;
            function createNewQuestion() {
                var DIV = document.createElement("div");
                var BR = document.createElement("BR");
                DIV.setAttribute('class' , 'round3');
                DIV.setAttribute("id", questionCount);
                DIV.innerHTML = `<input type="text" name="${questionCount}" placeholder="سوال خود را وارد کنید "
                class="form-control"><br><button type="button" onclick='deleteQuestion(${questionCount});'
                class='btn btn-danger'>حذف سوال</button>`;
                BR.setAttribute("id", `br-${questionCount}`)
                document.getElementById("questions").appendChild(DIV);
                document.getElementById("questions").appendChild(BR);
                questionCount++;
                list.push(questionCount);
                if (list.length <1 ) {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= true;
                } else {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= false;
                }
            }

            function submitForm() {
                var INPUT = document.createElement("input");
                INPUT.setAttribute("type", "hidden");
                INPUT.setAttribute("name", "questionCount")
                INPUT.setAttribute("value", questionCount)
                document.getElementById("form").appendChild(INPUT);
                document.getElementById("form").submit();
            }

            function deleteQuestion(name) {
                document.getElementById(`br-${name}`).remove()
                document.getElementById(name).remove()
                list.pop();
                if (list.length <1 ) {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= true;
                } else {
                    var btn = document.getElementById("submit-btn");
                    btn.disabled= false;
                }
            }
        </script>
    {% endblock %}
  {% endblock %}
{% endif %}

form/templates/form/form.html
{% extends "form/base.html" %}
{% load static %}
{% load i18n %}
{% if LANGUAGE_CODE == 'en'%}
  {% block content %}
    <div class="container">
      <h1 style="text-align: center;">{{form.name}}</h1>
      <div class="round3">
        {% for question in questions %}
          <div >
            <br>
            <div>
                <input placeholder="Question : {{ question.label }}" name="{{ question.id }}" class="form-control" disabled>
            </div>
            <br>
          </div>
        {% endfor %}
      </div>
      {% if participants == 0 %}
        No response yet
      {% else %}
        <br>
          <a class="btn btn-dark btn-sm" href="{% url 'form:all_submission' questions.0.form.id response.0.id %}"
          role="button" style="color:white">View submissions</a>
<!--          <a href="http://localhost:8000/d/{{form_id}}/{{rs.0.id}}/submissions/" style="color:black">View submissions</a><br>-->
      {% endif %}
      <br>
      Form link : <a id="to-copy" href="{% url 'form:view-form' questions.0.form.id %}" style="color:black">Open</a>
      <button class="btn btn-warning btn-sm"
              data-toggle="tooltip"
              data-placement="right"
              title="Copy form link"
              onclick="Copy()">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
              </svg>
      </button>
      <br>
      Participants : {{participants}}<br>
      <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();
        });
      </script>
      <script>
        function Copy() {
          var Txt = document.getElementById('to-copy')
          navigator.clipboard.writeText(Txt.href)
          alert("Form link copied")
        }
      </script>
    </div>
  {% endblock %}
{% else %}
  {% block contant %}
    <div class="container">
      <h1 style="text-align: center;">{{form.name}}</h1>
      <div class="round3">
        {% for question in questions %}
          <div >
            <br>
            <div>
                <input placeholder="سوال : {{ question.label }}" name="{{ question.id }}" class="form-control" disabled>
            </div>
            <br>
          </div>
        {% endfor %}
      </div>
      {% if participants == 0 %}
        پاسخی یافت نشد
      {% else %}
      <br>
          <a class="btn btn-dark" href="{% url 'form:all_submission' questions.0.form.id response.0.id %}"
          role="button" style="color:white">نمابش نتایج</a>
      {% endif %}
      <br>
      لینک فرم : <a id="to-copy2" href="{% url 'form:view-form' questions.0.form.id %}" style="color:black">اینجا</a>
      <button class="btn btn-warning btn-sm"
              data-toggle="tooltip2"
              data-placement="right"
              title="کپی"
              onclick="Copy2()">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
              </svg>
      </button>
      <br>
      Participants : {{participants}}<br>
      <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip2"]').tooltip();
        });
      </script>
      <script>
        function Copy2() {
          var Txt = document.getElementById('to-copy2')
          navigator.clipboard.writeText(Txt.href)
          alert("لینک فرم کپی شد")
        }
      </script>
  {% endblock %}
{% endif %}

form/templates/form/index.html
{% extends "form/base.html" %}
{% load static %}
{% load i18n %}

{% if LANGUAGE_CODE == 'en'%}
  {% block content %}

  {% if message %}
  <div>
    <h5>{{ message|safe }}</h5>
  </div>
  {% endif %}

  {% if Your_link %}
    <div>
      Your link: <a href="http://localhost:8000/form/v/{{form_id}}/">http://localhost:8000/form/v/{{form_id}}</a>
    </div>
  {% endif %}
<!-- <p style="width:50%;height:500px;background-image:url('fom.jpg');">hi</p> -->

  <!--
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  -->
      <p>welcome to form maker</p><br>
      <p>here you can create your own form</p>
      <li>send it to who you want</li>
      <li>ask them to fill the form</li>
      <li>see the results on view stats</li>
      <br>
      <p>thats all:)</p>


  {% endblock %}

{% else %}
  {% block contant %}

  {% if message %}
  <div>
    <h5>{{ message|safe }}</h5>
  </div>
  {% endif %}

  {% if Your_link %}
    <div>
      Your link: <a href="http://localhost:8000/form/v/{{form_id}}/">http://localhost:8000/form/v/{{form_id}}</a>
    </div>
  {% endif %}

  <!--
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  -->
      <p>به فرم ساز خوش اومدین</p><br>
      <p>اینجا میتونید فرم خودتون رو بسازین</p>
      <li>برای کسانی که میخوایین ارسال کنید</li>
      <li>از اونا بخوایین فرم رو پر کنن</li>
      <li>پاسخ های اونا رو در قسمت دیدن نتایج ببینید</li>
      <br>
      <p>به همین سادگی:)</p>

  {% endblock %}
{% endif %}

form/templates/form/my_form.html
{% extends "form/base.html" %}
{% load static %}
{% load i18n %}
{% if LANGUAGE_CODE == 'en'%}
  {% block content %}
    <div class="container">
        <div class="row">
          {% if forms %}
            {% for form in forms %}
              <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title">Form : {{form.name}}</h5>
                      <a href="{% url 'form:form_details' form.id %}" class="btn btn-dark" style="color:white">View Stats</a>
                      <a href="{% url 'form:delete-form' form.id %}" class="btn btn-warning">Delete Form </a>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <div class="col-sm-4">
              You have no form yet:(
              <a href="{% url 'form:create-form' %}">Create one?</a>
          {% endif %}
        </div>
    </div>
  {% endblock %}
{% else %}
  {% block contant %}
        <div class="container">
          <div class="row">
            {% if forms %}
              {% for form in forms %}
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">فرم : {{form.name}}</h5>
                        <a href="{% url 'form:form_details' form.id %}" class="btn btn-dark" style="color:white">نمایش وضعیت </a>
                        <a href="{% url 'form:delete-form' form.id %}" class="btn btn-warning">حذف فرم </a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <div class="col-sm-4">
                فرمی موجود نیست!
                <a href="{% url 'form:create-form' %}">ساخت فرم</a>
            {% endif %}
          </div>
        </div>
  {% endblock %}
{% endif %}

form/templates/form/view-form.html
{% extends 'form/base.html' %}
{% load static %}
{% load i18n %}
{% if LANGUAGE_CODE == 'en'%}
  {% block content %}
    {% block main %}
        <h1>{{name}}</h1>
          <form method="POST" action="{% url 'form:submit-form' form %}">
<!--          <input placeholder="Enter your name" name="paname" class="form-control"> -->
            {% csrf_token %}
              {% for question in questions %}
                  <div>
                      <input placeholder="{{ question.label }}" name="{{ question.id }}" class="form-control">
                  </div>
                  <br>
              {% endfor %}
              {% if user.is_authenticated %}
                <button type="submit" class="btn btn-primary" disabled>Submit</button>
              {% else %}
                <button type="submit" class="btn btn-primary" >Submit</button>
              {% endif %}
          </form>
  <!--      <button type="submit" class="btn btn-primary">Pdf</button>-->
    {% endblock %}
  {% endblock %}
{% else %}
  {% block contant %}
    {% block maain %}
        <h1>{{name}}</h1>
          <form method="POST" action="{% url 'form:submit-form' form %}">
  <!--        <form method="POST" action="/form/s/{{ form_id }}/">-->
            {% csrf_token %}
              {% for question in questions %}
                  <div>
                      <input placeholder="{{ question.label }}" name="{{ question.id }}" class="form-control">
                  </div>
                  <br>
              {% endfor %}
              <button type="submit" class="btn btn-primary">ثبت</button>
          </form>
  <!--      <button type="submit" class="btn btn-primary">Pdf</button>-->
    {% endblock %}
  {% endblock %}
{% endif %}